// flow-typed signature: 07fe700325d6800ee40ab2fb92dbdb62
// flow-typed version: <<STUB>>/d3-array_v2.7.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-array'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-array' {
  declare module.exports: any;
}
