// flow-typed signature: 907d29f8d3e51e4214741d633c400932
// flow-typed version: <<STUB>>/d3-collection_v1.0.7/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-collection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-collection' {
  declare module.exports: any;
}
