// flow-typed signature: 6b30cbe8947503cf5b22702a7931f20a
// flow-typed version: <<STUB>>/d3-selection_v2.0.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-selection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-selection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-selection/dist/d3-selection' {
  declare module.exports: any;
}

declare module 'd3-selection/dist/d3-selection.min' {
  declare module.exports: any;
}

declare module 'd3-selection/src/array' {
  declare module.exports: any;
}

declare module 'd3-selection/src/constant' {
  declare module.exports: any;
}

declare module 'd3-selection/src/create' {
  declare module.exports: any;
}

declare module 'd3-selection/src/creator' {
  declare module.exports: any;
}

declare module 'd3-selection/src/identity' {
  declare module.exports: any;
}

declare module 'd3-selection/src' {
  declare module.exports: any;
}

declare module 'd3-selection/src/local' {
  declare module.exports: any;
}

declare module 'd3-selection/src/matcher' {
  declare module.exports: any;
}

declare module 'd3-selection/src/namespace' {
  declare module.exports: any;
}

declare module 'd3-selection/src/namespaces' {
  declare module.exports: any;
}

declare module 'd3-selection/src/pointer' {
  declare module.exports: any;
}

declare module 'd3-selection/src/pointers' {
  declare module.exports: any;
}

declare module 'd3-selection/src/select' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selectAll' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/append' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/attr' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/call' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/classed' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/clone' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/data' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/datum' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/dispatch' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/each' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/empty' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/enter' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/exit' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/filter' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/html' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/insert' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/iterator' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/join' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/lower' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/merge' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/node' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/nodes' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/on' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/order' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/property' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/raise' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/remove' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/select' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/selectAll' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/selectChild' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/selectChildren' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/size' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/sort' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/sparse' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/style' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selection/text' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selector' {
  declare module.exports: any;
}

declare module 'd3-selection/src/selectorAll' {
  declare module.exports: any;
}

declare module 'd3-selection/src/sourceEvent' {
  declare module.exports: any;
}

declare module 'd3-selection/src/window' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-selection/dist/d3-selection.js' {
  declare module.exports: $Exports<'d3-selection/dist/d3-selection'>;
}
declare module 'd3-selection/dist/d3-selection.min.js' {
  declare module.exports: $Exports<'d3-selection/dist/d3-selection.min'>;
}
declare module 'd3-selection/src/array.js' {
  declare module.exports: $Exports<'d3-selection/src/array'>;
}
declare module 'd3-selection/src/constant.js' {
  declare module.exports: $Exports<'d3-selection/src/constant'>;
}
declare module 'd3-selection/src/create.js' {
  declare module.exports: $Exports<'d3-selection/src/create'>;
}
declare module 'd3-selection/src/creator.js' {
  declare module.exports: $Exports<'d3-selection/src/creator'>;
}
declare module 'd3-selection/src/identity.js' {
  declare module.exports: $Exports<'d3-selection/src/identity'>;
}
declare module 'd3-selection/src/index' {
  declare module.exports: $Exports<'d3-selection/src'>;
}
declare module 'd3-selection/src/index.js' {
  declare module.exports: $Exports<'d3-selection/src'>;
}
declare module 'd3-selection/src/local.js' {
  declare module.exports: $Exports<'d3-selection/src/local'>;
}
declare module 'd3-selection/src/matcher.js' {
  declare module.exports: $Exports<'d3-selection/src/matcher'>;
}
declare module 'd3-selection/src/namespace.js' {
  declare module.exports: $Exports<'d3-selection/src/namespace'>;
}
declare module 'd3-selection/src/namespaces.js' {
  declare module.exports: $Exports<'d3-selection/src/namespaces'>;
}
declare module 'd3-selection/src/pointer.js' {
  declare module.exports: $Exports<'d3-selection/src/pointer'>;
}
declare module 'd3-selection/src/pointers.js' {
  declare module.exports: $Exports<'d3-selection/src/pointers'>;
}
declare module 'd3-selection/src/select.js' {
  declare module.exports: $Exports<'d3-selection/src/select'>;
}
declare module 'd3-selection/src/selectAll.js' {
  declare module.exports: $Exports<'d3-selection/src/selectAll'>;
}
declare module 'd3-selection/src/selection/append.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/append'>;
}
declare module 'd3-selection/src/selection/attr.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/attr'>;
}
declare module 'd3-selection/src/selection/call.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/call'>;
}
declare module 'd3-selection/src/selection/classed.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/classed'>;
}
declare module 'd3-selection/src/selection/clone.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/clone'>;
}
declare module 'd3-selection/src/selection/data.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/data'>;
}
declare module 'd3-selection/src/selection/datum.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/datum'>;
}
declare module 'd3-selection/src/selection/dispatch.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/dispatch'>;
}
declare module 'd3-selection/src/selection/each.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/each'>;
}
declare module 'd3-selection/src/selection/empty.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/empty'>;
}
declare module 'd3-selection/src/selection/enter.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/enter'>;
}
declare module 'd3-selection/src/selection/exit.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/exit'>;
}
declare module 'd3-selection/src/selection/filter.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/filter'>;
}
declare module 'd3-selection/src/selection/html.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/html'>;
}
declare module 'd3-selection/src/selection/index' {
  declare module.exports: $Exports<'d3-selection/src/selection'>;
}
declare module 'd3-selection/src/selection/index.js' {
  declare module.exports: $Exports<'d3-selection/src/selection'>;
}
declare module 'd3-selection/src/selection/insert.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/insert'>;
}
declare module 'd3-selection/src/selection/iterator.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/iterator'>;
}
declare module 'd3-selection/src/selection/join.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/join'>;
}
declare module 'd3-selection/src/selection/lower.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/lower'>;
}
declare module 'd3-selection/src/selection/merge.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/merge'>;
}
declare module 'd3-selection/src/selection/node.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/node'>;
}
declare module 'd3-selection/src/selection/nodes.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/nodes'>;
}
declare module 'd3-selection/src/selection/on.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/on'>;
}
declare module 'd3-selection/src/selection/order.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/order'>;
}
declare module 'd3-selection/src/selection/property.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/property'>;
}
declare module 'd3-selection/src/selection/raise.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/raise'>;
}
declare module 'd3-selection/src/selection/remove.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/remove'>;
}
declare module 'd3-selection/src/selection/select.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/select'>;
}
declare module 'd3-selection/src/selection/selectAll.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/selectAll'>;
}
declare module 'd3-selection/src/selection/selectChild.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/selectChild'>;
}
declare module 'd3-selection/src/selection/selectChildren.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/selectChildren'>;
}
declare module 'd3-selection/src/selection/size.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/size'>;
}
declare module 'd3-selection/src/selection/sort.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/sort'>;
}
declare module 'd3-selection/src/selection/sparse.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/sparse'>;
}
declare module 'd3-selection/src/selection/style.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/style'>;
}
declare module 'd3-selection/src/selection/text.js' {
  declare module.exports: $Exports<'d3-selection/src/selection/text'>;
}
declare module 'd3-selection/src/selector.js' {
  declare module.exports: $Exports<'d3-selection/src/selector'>;
}
declare module 'd3-selection/src/selectorAll.js' {
  declare module.exports: $Exports<'d3-selection/src/selectorAll'>;
}
declare module 'd3-selection/src/sourceEvent.js' {
  declare module.exports: $Exports<'d3-selection/src/sourceEvent'>;
}
declare module 'd3-selection/src/window.js' {
  declare module.exports: $Exports<'d3-selection/src/window'>;
}
