// flow-typed signature: c5e0917633fcc4b3962290b8ac57a263
// flow-typed version: <<STUB>>/d3-scale_v3.2.2/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-scale'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-scale' {
  declare module.exports: any;
}
