// flow-typed signature: c2d2412c06877d819d3cd4360b374aeb
// flow-typed version: <<STUB>>/d3-transition_v2.0.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-transition'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-transition' {
  declare module.exports: any;
}
