// flow-typed signature: 33ef3a2d3f6bf1c8a39549ccc666bc3d
// flow-typed version: <<STUB>>/d3_v5.16.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3' {
  declare module.exports: any;
}
