// flow-typed signature: b8127b5d14b8b3f8e090da6b48fa7966
// flow-typed version: <<STUB>>/hamt_plus_v1.0.2/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hamt_plus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hamt_plus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hamt_plus/hamt' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hamt_plus/hamt.js' {
  declare module.exports: $Exports<'hamt_plus/hamt'>;
}
