// flow-typed signature: 01f138bab8c1a273bb901b529eed460c
// flow-typed version: <<STUB>>/jsondiffpatch-for-react_v1.0.4/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsondiffpatch-for-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsondiffpatch-for-react' {
  declare module.exports: any;
}
