// flow-typed signature: 0b4008173515b0c71528fd8763afbff9
// flow-typed version: <<STUB>>/nullthrows_v1.1.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nullthrows'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nullthrows' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nullthrows/nullthrows' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nullthrows/nullthrows.js' {
  declare module.exports: $Exports<'nullthrows/nullthrows'>;
}
