// flow-typed signature: 3d9217fcc3103eff665390686051441d
// flow-typed version: <<STUB>>/ReactDOM_v17.0.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ReactDOM'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ReactDOM' {
  declare module.exports: any;
}
