// flow-typed signature: 957098ea98fd4cfa09140997329ef825
// flow-typed version: <<STUB>>/ReactTestUtils_v17.0.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ReactTestUtils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ReactTestUtils' {
  declare module.exports: any;
}
