// flow-typed signature: 5ddd4ed01445797d517fcd7717fd5ec8
// flow-typed version: <<STUB>>/recoil_v0.0.13/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'recoil'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'recoil' {
  declare module.exports: any;
}
